#### Makefile

all: unpack

unpack:
	echo "Unpacking dependencies..."
	tar zxvf svdlibc.tar.gz
	tar zxvf nlopt-2.4.2.tar.gz
	tar zxvf ffmpeg-3.1.1.tar.gz
	tar zxvf libsndfile-1.0.27.tar.gz
	tar zxvf liquid-dsp-1.2.0.tar.gz

clean:
	echo "Removing folders..."
	rm -rf SVDLIBC
	rm -rf nlopt-2.4.2
	rm -rf ffmpeg-3.1.1
	rm -rf libsndfile-1.0.27
	rm -rf liquid-dsp-1.2.0
