close all;
clear all;

%% Pitch
%Sub 1
pitch_atr = [363.3 378.8 395.1 385.8];
drift_atr = [347.2 378.4 386.1 378.0];
z = pitch_atr - pitch_atr(3);
figure;
subplot(3,1,1);
plot(pitch_atr,'o','MarkerFaceColor','b');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
title('A) Subject 1: Pitch','fontweight','bold','fontsize',12);
xlabel('ATR');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

%EIL
pitch_eil = [416.5 468.7 490.2 561.1];
drift_eil = [302.0 349.6 364.2 407.7];
z = [z; pitch_eil - pitch_eil(3)];

subplot(3,1,2);
plot(pitch_eil,'o','MarkerFaceColor','b');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 440.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 466.16]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 493.88]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 523.25]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 554.37]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('EIL');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

% WNDL
pitch_wndl = [325.1 296.6 286.6 318.2];
drift_wndl = [302.8 288.8 277.2 300.1];
z = [z; pitch_wndl - pitch_wndl(3)];
subplot(3,1,3);
plot(pitch_wndl,'o','MarkerFaceColor','b');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('WNDL');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

% drift
figure;
y(:,1) = pitch_atr;
y(:,2) = drift_atr;
plot(y','-o');
ylabel('Pitch (Hz)');
title('A) Subject 1, ATR: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_eil;
y(:,2) = drift_eil;
plot(y','-o');
title('B) Subject 1, EIL: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 311.13]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 440.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 466.16]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 493.88]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 523.25]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 554.37]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_wndl;
y(:,2) = drift_wndl;
plot(y','o-');
title('C) Subject 1, WNDL: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 311.13]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

% Averages
figure;
errorbar(mean(z), std(z),'o','MarkerFaceColor','b');
hold on;
plot(median(z),'ro','MarkerFaceColor','r');
legend('Mean', 'Median');
set(gca,'XTickLabel',{'', 'NG14','','RR','','AC','','LG14'});
title('A) Subject 1: Pitch Differences Relative to AC','fontweight','bold','fontsize',12);
ylabel('Frequency (Hz)');
hline = refline([0 0]);
set(hline,'Color','k');


%Sub 2
pitch_atr = [298.1 318.8 314.6 398.3];
drift_atr = [296.1 306.4 310.2 390.2];
figure;
subplot(3,1,1);
plot(pitch_atr,'o','MarkerFaceColor','b');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 311.13]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
title('B) Subject 2: Pitch','fontweight','bold','fontsize',12);
xlabel('ATR');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'AC', '', 'NG14', '', 'LG14', '', 'RR'});

%EIL
pitch_eil = [473.8 472.9 523.8 531.8];
drift_eil = [470.4 493.3 542.2 540.8];
subplot(3,1,2);
plot(pitch_eil,'o','MarkerFaceColor','b');
hline = refline([0 466.16]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 493.88]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 523.25]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 554.37]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('EIL');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'AC', '', 'NG14', '', 'LG14', '', 'RR'});

% JTOU
pitch_jtou = [232.1 235.3 262.6 246.5];
drift_jtou = [235.2 234.4 259.1 242.1];
subplot(3,1,3);
plot(pitch_jtou,'o','MarkerFaceColor','b');
hline = refline([0 220.0]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 233.08]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 246.94]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 261.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('JTOU');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'AC', '', 'NG14', '', 'LG14', '', 'RR'});

%Sub 2 Reordered
pitch_atr = [318.8 398.3 298.1 314.6];
z = [pitch_atr - pitch_atr(3)];
figure;
subplot(3,1,1);
plot(pitch_atr,'o','MarkerFaceColor','b');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 311.13]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
title('D) Subject 2: Pitch (rooms reordered)','fontweight','bold','fontsize',12);
xlabel('ATR');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

%EIL
pitch_eil = [472.9 531.8 473.8 523.8];
z = [z; pitch_eil - pitch_eil(3)];
subplot(3,1,2);
plot(pitch_eil,'o','MarkerFaceColor','b');
hline = refline([0 466.16]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 493.88]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 523.25]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 554.37]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('EIL');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

% JTOU
pitch_jtou = [235.3 246.5 232.1 262.6];
z = [z; pitch_jtou - pitch_jtou(3)];
subplot(3,1,3);
plot(pitch_jtou,'o','MarkerFaceColor','b');
hline = refline([0 220.0]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 233.08]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 246.94]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 261.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('JTOU');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});


% drift
figure;
y(:,1) = pitch_atr;
y(:,2) = drift_atr;
plot(y','o-');
ylabel('Pitch (Hz)');
title('D) Subject 2, ATR: Pitch Drift','fontweight','bold','fontsize',12);
legend('AC', 'NG14', 'LG14', 'RR','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 311.13]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 329.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 349.23]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 369.99]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 392.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 415.30]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_eil;
y(:,2) = drift_eil;
plot(y','-o');
title('E) Subject 2, EIL: Pitch Drift','fontweight','bold','fontsize',12');
legend('AC', 'NG14', 'LG14', 'RR','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 466.16]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 493.88]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 523.25]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 554.37]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_jtou;
y(:,2) = drift_jtou;
plot(y','-o');
title('F) Subject 2, JTOU: Pitch Drift','fontweight','bold','fontsize',12);
legend('AC', 'NG14', 'LG14', 'RR','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 220.0]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 233.08]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 246.94]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 261.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

% Averages
figure;
errorbar(mean(z), std(z),'o','MarkerFaceColor','b');
hold on;
plot(median(z),'ro','MarkerFaceColor','r');
legend('Mean', 'Median');
set(gca,'XTickLabel',{'', 'NG14','','RR','','AC','','LG14'});
title('B) Subject 2: Pitch Differences Relative to AC','fontweight','bold','fontsize',12);
ylabel('Frequency (Hz)');
hline = refline([0 0]);
set(hline,'Color','k');


%Sub 3
pitch_atr = [187.6 188.2 183.2 200.4];
drift_atr = [193.7 199.5 192.2 205.3];
z = [pitch_atr - pitch_atr(3)];
figure;
subplot(3,1,1);
plot(pitch_atr,'o','MarkerFaceColor','b');
hline = refline([0 174.61]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 185.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 196.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 207.65]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
title('C) Subject 3: Pitch','fontweight','bold','fontsize',12);
xlabel('ATR');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

%EIL
pitch_eil = [267.7 278.3 266.3 275.3];
drift_eil = [269.9 276.1 272.0 276.8];
z = [z; pitch_eil - pitch_eil(3)];

subplot(3,1,2);
plot(pitch_eil,'o','MarkerFaceColor','b');
hline = refline([0 261.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('EIL');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});

% WDC
pitch_wdc = [198.5 208.8 207.7 208.0];
drift_wdc = [212.6 205.4 214.6 207.6];
z = [z; pitch_wdc - pitch_wdc(3)];
subplot(3,1,3);
plot(pitch_wdc,'o','MarkerFaceColor','b');
hline = refline([0 196.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 207.65]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 220.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
xlabel('WDC');
ylabel('Pitch (Hz)');
set(gca,'XTickLabel',{'NG14', '', 'RR', '', 'AC', '', 'LG14'});


% drift
figure;
y(:,1) = pitch_atr;
y(:,2) = drift_atr;
plot(y','-o');
ylabel('Pitch (Hz)');
title('G) Subject 3, ATR: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
hline = refline([0 174.61]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 185.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 196.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 207.65]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_eil;
y(:,2) = drift_eil;
plot(y','-o');
title('H) Subject 3, EIL: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 261.63]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 277.18]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 293.66]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

figure;
y(:,1) = pitch_wdc;
y(:,2) = drift_wdc;
plot(y','-o');
title('I) Subject 3, WDC: Pitch Drift','fontweight','bold','fontsize',12);
legend('NG14', 'RR', 'AC', 'LG14','Location','North');
set(gca,'XTickLabel',{'', '', '', '', '', '', '', '', '', '', ''});
ylabel('Pitch (Hz)');
hline = refline([0 196.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 207.65]);
set(hline,'Color','k');
set(hline,'LineStyle',':');
hline = refline([0 220.00]);
set(hline,'Color','k');
set(hline,'LineStyle',':');

% Averages
figure;
errorbar(mean(z), std(z),'o','MarkerFaceColor','b');
hold on;
plot(median(z),'ro','MarkerFaceColor','r');
legend('Mean', 'Median');
set(gca,'XTickLabel',{'', 'NG14','','RR','','AC','','LG14'});
title('C) Subject 3: Pitch Differences Relative to AC','fontweight','bold','fontsize',12);
ylabel('Frequency (Hz)');
hline = refline([0 0]);
set(hline,'Color','k');
